[profile.default]
ffi = false
fuzz_runs = 256
optimizer = true
optimizer_runs = 1000000
verbosity = 1
libs = ["../../node_modules", "../../../mud"]
src = "src"
test = "test"
out = "out"
extra_output_files = [
  "abi",
  "evm.bytecode"
]
fs_permissions = [{ access = "read", path = "./"}]

[profile.lattice-testnet]
eth_rpc_url = "https://follower.testnet-chain.linfra.xyz"
[profile.frontier]
eth_rpc_url = "http://localhost:9933"
[profile.core-evm]
eth_rpc_url = "ws://localhost:6789"
[profile.moonbase-alpha]
eth_rpc_url = "https://rpc.api.moonbase.moonbeam.network"